### ISSUE TITLE
[Suggestion] Make php installing optional

### ISSUE THREAD

**Issue by frutality** [dj-wasabi/ansible-zabbix-web#11]
Hi!

I suggest add variable `zabbix_install_php` which can be set to `false`. Some servers already have php installed (for example, with ansible role geerlingguy.php). I had php7.1 installed and running, and after installing zabbix-web, I had to manually remove php7.0 packages.

Updated: actually, I'm only trying to remove 7.0 packages. It is now a mess. Removing any php-7.0 package with `apt-get` suggests to upgrade php to 7.2. This is annoying. And I can't remove them with `dpkg` because "dependency problems prevent removal of ..."

**Comment by dj-wasabi** [comment]
Good idea. Do you want to provide a PR, or shall I do this?

**Comment by frutality** [comment]
Well, not sure about this. I just finished to install `zabbix-frontend-php` manually and not sure I can write a playbook task for this. Main problem is they do not provide direct link to tar.gz file, only sourceforge. So I had to download archive with browser and then rsync it to server. Next steps are simple however - just tar, copy, chown commands.

There is a way to install `zabbix-frontend-php` from repo without dependencies (https://askubuntu.com/questions/74523/how-can-i-install-a-package-without-installing-some-dependencies) but I'm not sure if this can broke something.

But I'm not experienced ansible user, so advises are appreciated.

**Comment by ericsysmin** [comment]
@dj-wasabi @frutality I don't think the way we install the objects in ansible will allow this, we may need to use `command` if we want to permit installing without php dependency

**Comment by kr4ut** [comment]
@frutality We'll have a look into that after finished #58 and deal with php7.2 integration for bionic. Let's see but if the Debian packages have the dependency i tend to not mess more with it. IMHO you should not put the web interface of Zabbix on a shared instance but use a dedicated one where you can define it from scratch. Also there is no need for a full blown PHP role for the few bits we need for Zabbix Web.

**Comment by kr4ut** [comment]
@frutality Got good and bad news for you. First the PR is out to make the installing of PHP packages by the Ansible role it self optional via the new `zabbix_php_install` variable that defaults to true. But while inspecting it the problem is that we're actually managing the PHP stuff from at least three different sides:
- from this role (which is now optional)
- from the zabbix-frontend-php package (only fixable upstream)
- from local admin action (like you using other roles for it)

So even if you disable `zabbix_php_install` now you still might have problems from:
`root@test-u8:~# dpkg -s zabbix-frontend-php | grep -B1 "Depends"
Version: 1:4.2.3-2+bionic
Depends: php-mbstring, php-bcmath, php-xml, apache2 | httpd, php5 | libapache2-mod-php | php, php5-mysql | php5-mysqlnd | php-mysql | php5-pgsql | php-pgsql, php5-gd | php-gd, php5-ldap | php-ldap, ttf-dejavu-core | ttf-japanese-gothi`

@frutality For your understanding the package itself declares dependencies not recommendations but does it in a way that it actually works with both the old single and the multi version PHP packages in the Debian family. BTW this was also part of #57 as we did enrich the packaging of PHP some years ago and only old releases still hardcore the major version in the package name like Ubuntu trusty and Debian squeeze. Since that we have parallel installable versions of the PHP packages, just that Canonical didn't follow our request and just bundles one version which is covered by their security team.

Guessing that you're are on Ubuntu and there actually was never a supported 7.1 release on this distro. Which leads to the assumption that the role from Jeff just installs stuff from probably Ondřej's PPA. Didn't look at the role for ages but this is IMHO one of the issues while we don't regard those roles production grade. Don't get us wrong as Ondřej does an awesome job, but you should really know what you're doing when you're using it at production grade.

For this role this kind of support is IMHO out of scope as by the use case of Zabbix we shouldn't deal with custom PHP version and external repositories apart from Zabbix. But i hope this makes the whole situation more understandable as the PR should otherwise close this issue :wave:
